Repository FC-DEV3-Final-Project/zoop-frontend, pull requests merged in 2025-06, with the labels that each got.

#11 chore: tailwind 스타일가이드 작성
  package-lock.json
  package.json
  postcss.config.js
  public/icons/alram-active.svg
  public/icons/alram.svg
  public/icons/arrow-down.svg
  public/icons/arrow-left.svg
  public/icons/arrow-right.svg
  public/icons/arrow-up.svg
  public/icons/chat-teardrop.svg
  public/icons/chat-text-filled.svg
  public/icons/chat-text.svg
  public/icons/contract.svg
  public/icons/excel3.svg
  public/icons/expand.svg
  public/icons/heart-filled.svg
  public/icons/heart-outline.svg
  public/icons/image.svg
  public/icons/list.svg
  public/icons/map.svg
  public/icons/minus.svg
  public/icons/more.svg
  public/icons/report.svg
  public/icons/search.svg
  public/icons/send.svg
  public/icons/setting.svg
  public/icons/share.svg
  public/icons/star-filled.svg
  public/icons/star-outline.svg
  public/icons/thumbsup-filled.svg
  public/icons/thumbsup-outline.svg
  public/icons/trash.svg
  public/icons/unmute.svg
  public/icons/write.svg
  public/icons/x.svg
  src/app/globals.css
  src/app/test/page.tsx
  tailwind.config.js
Labels: 🎨 HTML & CSS

#6 feat: tab 컴포넌트 제작
  src/app/test/page.tsx
  src/components/Tab.tsx
Labels: ✨ Feature

#10 feat: 공통 컴포넌트 버튼 구현
  package-lock.json
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/ui/button.tsx
  src/layout/Header.tsx
Labels: ✨ Feature

#7 feat: 공통컴포넌트 매물카드
  .vscode/settings.json
  package-lock.json
  package.json
  public/icons/heart_false.svg
  public/icons/heart_true.svg
  public/imgs/propertyExample.png
  src/app/layout.tsx
  src/app/mypage/[id]/page.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/common/HeartButton.tsx
  src/components/common/PropertyCard.tsx
  src/hooks/property/useLike.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#20 chore: 아이콘 변경
  public/icons/alram-active.svg
  public/icons/arrow-rignt.svg
  public/icons/chat-text-filled.svg
  public/icons/chat-text.svg
  public/icons/heart-filled.svg
  public/icons/heart-outline.svg
  public/icons/heart_false.svg
  public/icons/heart_true.svg
  public/icons/minus.svg
  public/icons/send.svg
  public/icons/star-filled.svg
  public/icons/star-outline.svg
  public/icons/star-unfilled.svg
  public/icons/thumbsup-filled.svg
  public/icons/thumbsup-outline.svg
  public/icons/trash.svg
  src/components/common/HeartButton.tsx
Labels: 🎨 HTML & CSS

#16 feat: 매물 상세 탭
  package-lock.json
  package.json
  public/icons/arrow-right.svg
  public/icons/building.svg
  public/icons/elevator.svg
  public/icons/house-new.svg
  public/icons/money.svg
  public/icons/park.svg
  public/icons/parking.svg
  public/icons/pet.svg
  public/icons/ruler.svg
  public/icons/school.svg
  public/icons/smile.svg
  public/icons/stairs.svg
  src/app/property/[id]/components/ImageCarousel.tsx
  src/app/property/[id]/components/detail/DetailTab.tsx
  src/app/property/[id]/components/detail/GrayButton.tsx
  src/app/property/[id]/components/detail/InfoBox.tsx
  src/app/property/[id]/components/detail/ScrollableTabBar.tsx
  src/app/property/[id]/components/detail/SectionList.tsx
  src/app/property/[id]/components/detail/section/AgentSection.tsx
  src/app/property/[id]/components/detail/section/DealSection.tsx
  src/app/property/[id]/components/detail/section/DescriptionSection.tsx
  src/app/property/[id]/components/detail/section/InfoSection.tsx
  src/app/property/[id]/components/detail/section/LocationSection.tsx
  src/app/property/[id]/components/detail/section/PriceSection.tsx
  src/app/property/[id]/components/review/ReviewTab.tsx
  src/app/property/[id]/page.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 HTML & CSS

#28 design: 정보수정 페이지 퍼블리싱
  public/icons/chat-text-disabled.svg
  public/icons/thumbsup-disabled.svg
  public/imgs/default-profile.jpg
  public/imgs/default-profile.png
  src/app/mypage/[id]/page.tsx
  src/app/mypage/[id]/user-info/edit-nickname/page.tsx
  src/app/mypage/[id]/user-info/edit-profile-image/page.tsx
  src/app/mypage/[id]/user-info/page.tsx
  src/components/common/HeartButton.tsx
  src/components/common/PropertyListSection.tsx
  src/components/common/ReviewItem.tsx
  src/components/mypage/PostPreview.tsx
  src/hooks/common/useLike.ts
  src/hooks/user/mutations/.gitkeep
  src/hooks/user/queries/.gitkeep
Labels: 🎨 HTML & CSS

#29 design: 내가 쓴 글 페이지 퍼블리싱
  public/icons/reply-arrow.svg
  src/app/mypage/[id]/myposts/page.tsx
  src/components/common/PostPreview.tsx
  src/components/mypage/myposts/MyPostItem.tsx
Labels: 🎨 HTML & CSS

#34 design: 매물카드 거래완료 디자인
  public/icons/heart_false.svg
  public/icons/heart_true.svg
  src/app/test/page.tsx
  src/components/common/HeartButton.tsx
  src/components/common/PropertyCard.tsx
  src/hooks/property/useLike.ts
Labels: 🎨 HTML & CSS

#32 design: review 탭, review 상세, review 작성 페이지 퍼블리싱 및 detail 탭 수정
  package-lock.json
  package.json
  public/icons/share.svg
  public/icons/star-half.svg
  src/app/layout.tsx
  src/app/property/[id]/(with-tabs)/layout.tsx
  src/app/property/[id]/(with-tabs)/page.tsx
  src/app/property/[id]/(with-tabs)/review/page.tsx
  src/app/property/[id]/components/detail/DetailTab.tsx
  src/app/property/[id]/components/detail/SectionList.tsx
  src/app/property/[id]/components/detail/section/InfoSection.tsx
  src/app/property/[id]/components/detail/section/LocationSection.tsx
  src/app/property/[id]/components/detail/section/PriceSection.tsx
  src/app/property/[id]/components/review/ReviewTab.tsx
  src/app/property/[id]/page.tsx
  src/app/property/[id]/review/[reviewId]/page.tsx
  src/app/property/[id]/review/new/page.tsx
  src/app/test/page.tsx
  src/components/common/PropertyCard.tsx
  src/components/common/PropertyListSection.tsx
  src/components/common/Tab.tsx
  src/components/property/ImageCarousel.tsx
  src/components/property/detail/GrayButton.tsx
  src/components/property/detail/InfoBox.tsx
  src/components/property/detail/ScrollableTabBar.tsx
  src/components/property/detail/SectionList.tsx
  src/components/property/detail/section/AgentSection.tsx
  src/components/property/detail/section/DealSection.tsx
  src/components/property/detail/section/DescriptionSection.tsx
  src/components/property/detail/section/FacilitySection.tsx
  src/components/property/detail/section/InfoSection.tsx
  src/components/property/detail/section/LocationSection.tsx
  src/components/property/review/CommentList.tsx
  src/components/property/review/EnvironmentTabs.tsx
  src/components/property/review/ReviewCard.tsx
  src/components/property/review/ReviewList.tsx
  src/components/property/review/ReviewSortButtons.tsx
  src/components/property/review/new/ReviewTextarea.tsx
  src/components/property/review/new/SelectButtonGroup.tsx
  src/components/property/review/new/StarRating.tsx
  src/components/ui/tabs.tsx
  src/hooks/property/useCarousel.ts
  src/hooks/property/useStarRating.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#43 Feat: drop down 컴포넌트
  public/icons/more.svg
  src/app/test/page.tsx
  src/components/Dropdown.tsx
Labels: 🎨 HTML & CSS

#36 Feat/bottom sheet
  package.json
  src/app/test/page.tsx
  src/components/BottomSheet.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Dropdown.tsx
  src/components/ui/sheet.tsx
Labels: 🎨 HTML & CSS

#40 feat: 부동산페이지 추가 퍼블리싱
  src/app/real-estate/[id]/page.tsx
  src/components/real-estate/RealEstateInfo.tsx
Labels: 🎨 HTML & CSS

#44 api: msw 적용
  next.config.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/app/mypage/[id]/user-info/page.tsx
  src/components/MSWComponent.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/mypageHandlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
Labels: 📬 API

#51 feat: 매매 형태 단일 선택으로 수정
  src/app/chat/filter/page.tsx
  src/components/common/FilterOptionCard.tsx
  src/components/setup/LocationStep.tsx
  src/components/setup/OptionSelectStep.tsx
Labels: ✨ Feature

#49 design: 필터 설정 페이지 - 지역 설정 단계 추가 퍼블리싱
  src/app/chat/filter/page.tsx
  src/components/common/FilterOptionCard.tsx
  src/components/setup/LocationStep.tsx
  src/components/setup/OptionSelectStep.tsx
Labels: ✨ Feature, 🎨 HTML & CSS

#48 design: 마이페이지 추가 수정
  src/app/mypage/[id]/myposts/page.tsx
  src/app/mypage/[id]/user-info/edit-profile-image/page.tsx
  src/app/mypage/[id]/user-info/page.tsx
  src/components/mypage/myposts/MyPostItem.tsx
Labels: 🎨 HTML & CSS

#47 로그인 기능
  package-lock.json
  package.json
  public/icons/kakao-logo.svg
  src/apis/login/user.ts
  src/apis/utils/axiosInstance.ts
  src/app/layout.tsx
  src/app/login/complete/page.tsx
  src/app/login/nicknameForm/page.tsx
  src/app/login/page.tsx
  src/app/providers.tsx
  src/hooks/common/useAuthFromHash.ts
  src/types/user.ts
Labels: 📬 API

#58 feat: 공통컴포넌트 분리(닉네임, 전화걸기)
  src/app/mypage/[id]/user-info/edit-nickname/page.tsx
  src/app/real-estate/[id]/page.tsx
  src/components/common/NicknameInput.tsx
  src/components/common/RealEstateCallButton.tsx
Labels: ✨ Feature

#59 api: 매물 상세 페이지 fetch API 연동 및 mock 테스트 환경 구성
  src/apis/property/detail/fetchAgent.ts
  src/apis/property/detail/fetchBasicInfo.ts
  src/apis/property/detail/fetchBrokerFee.ts
  src/apis/property/detail/fetchDescription.ts
  src/apis/property/detail/fetchFacilities.ts
  src/apis/property/detail/fetchLocation.ts
  src/apis/property/detail/fetchPropertyInfo.ts
  src/apis/property/detail/fetchTransaction.ts
  src/app/property/[id]/(with-tabs)/layout.tsx
  src/app/property/[id]/(with-tabs)/page.tsx
  src/app/property/[id]/review/new/page.tsx
  src/components/property/ImageCarousel.tsx
  src/components/property/detail/InfoBox.tsx
  src/components/property/detail/ScrollableSection.tsx
  src/components/property/detail/SectionList.tsx
  src/components/property/detail/section/AgentSection.tsx
  src/components/property/detail/section/DealSection.tsx
  src/components/property/detail/section/DescriptionSection.tsx
  src/components/property/detail/section/FacilitySection.tsx
  src/components/property/detail/section/InfoSection.tsx
  src/components/property/detail/section/LocationSection.tsx
  src/components/property/review/CommentList.tsx
  src/components/property/review/ReviewCard.tsx
  src/components/property/review/ReviewList.tsx
  src/components/property/review/new/ReviewTextarea.tsx
  src/components/property/review/new/StarRating.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/property/detailHandler.ts
  src/queries/property/useBasicInfoQuery.ts
  src/utils/property/formatRelativeDate.ts
Labels: ✨ Feature, 📬 API

#69 feat: 닉네임 유효성검사 로직 추가
  src/app/mypage/[id]/user-info/edit-nickname/page.tsx
  src/components/common/NicknameInput.tsx
  src/mocks/handlers/commonHandlers.ts
  src/mocks/handlers/index.ts
Labels: ✨ Feature

#53 design: 채팅 화면, 히스토리 사이드바 퍼블리싱
  public/icons/close.svg
  public/icons/logo.svg
  public/icons/new-chat.svg
  public/imgs/.gitkeep
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/SideBar.tsx
  src/components/chat/SideBarItem.tsx
  src/components/ui/input.tsx
  src/components/ui/sheet.tsx
  src/layout/Header.tsx
Labels: 🎨 HTML & CSS

#68 feat: 무한스크롤 마이페이지 적용
  next.config.ts
  src/app/mypage/[id]/myposts/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/real-estate/[id]/page.tsx
  src/components/common/PostPreview.tsx
  src/components/common/PropertyListSection.tsx
  src/components/mypage/PostPreviewBox.tsx
  src/components/mypage/PostPreviewItem.tsx
  src/components/mypage/UserProfile.tsx
  src/components/mypage/myposts/MyPostItem.tsx
  src/components/real-estate/RealEstateInfo.tsx
  src/hooks/common/useInfiniteScroll.ts
  src/mocks/handlers/mypage/mypageHomeHandlers.ts
Labels: ✨ Feature

#52 feat: 예산 설정 단계 금액 입력 로직 추가
  src/app/chat/filter/page.tsx
  src/components/setup/AmountQuickSelect.tsx
  src/components/setup/BudgeStep.tsx
  src/components/setup/BudgetStep.tsx
  src/utils/budget.tsx
Labels: ✨ Feature

#71 feat: 로그인-닉네임 입력 페이지
  src/apis/login/createUserNickname.ts
  src/apis/login/getUserInfo.ts
  src/app/login/page.tsx
  src/app/login/set-nickname/page.tsx
  src/app/page.tsx
  src/stores/useUserInfoStore.ts
  tailwind.config.js
Labels: ✨ Feature

#75 feat: 매물 상세에 카카오 정적맵 반영
  src/app/layout.tsx
  src/components/property/detail/section/LocationSection.tsx
  src/mocks/handlers/property/detailHandler.ts
Labels: ✨ Feature

#78 refactor: property 페이지 개선 (useQuery 적용, axios instance 반영)
  src/apis/property/detail/fetchAgent.ts
  src/apis/property/detail/fetchBasicInfo.ts
  src/apis/property/detail/fetchBrokerFee.ts
  src/apis/property/detail/fetchDescription.ts
  src/apis/property/detail/fetchFacilities.ts
  src/apis/property/detail/fetchLocation.ts
  src/apis/property/detail/fetchPropertyInfo.ts
  src/apis/property/detail/fetchTransaction.ts
  src/apis/property/review/fetchComments.ts
  src/apis/property/review/fetchReviewList.ts
  src/apis/property/review/postReview.ts
  src/apis/utils/axiosInstance.ts
  src/app/property/[id]/(with-tabs)/page.tsx
  src/app/property/[id]/(with-tabs)/review/page.tsx
  src/app/property/[id]/review/[reviewId]/page.tsx
  src/app/property/[id]/review/new/page.tsx
  src/components/property/detail/section/AgentSection.tsx
  src/components/property/detail/section/DealSection.tsx
  src/components/property/detail/section/DescriptionSection.tsx
  src/components/property/detail/section/FacilitySection.tsx
  src/components/property/detail/section/InfoSection.tsx
  src/components/property/detail/section/LocationSection.tsx
  src/components/property/review/ReviewCard.tsx
  src/components/property/review/ReviewList.tsx
  src/components/property/review/new/ReviewTextarea.tsx
  src/components/property/review/new/StarRating.tsx
  src/mocks/handlers/property/detailHandler.ts
  src/mocks/handlers/property/reviewHandlers.ts
  src/queries/property/detail/useAgentQuery.ts
  src/queries/property/detail/useBasicInfoQuery.ts
  src/queries/property/detail/useBrokerFeeQuery.ts
  src/queries/property/detail/useDescriptionQuery.ts
  src/queries/property/detail/useFacilitiesQuery.ts
  src/queries/property/detail/useLocationQuery.ts
  src/queries/property/detail/usePropertyInfoQuery.ts
  src/queries/property/detail/useTransactionQuery.ts
  src/queries/property/review/useCommentListQuery.ts
  src/queries/property/review/usePostReviewMutation.ts
  src/queries/property/review/useReviewListQuery.ts
Labels: ✨ Feature, 🔨 Refactor

#80 api: 마이페이지 api 연동 및 리팩토링
  next.config.ts
  src/apis/mypage/fetchBookmarkedProperties.ts
  src/apis/mypage/fetchLogout.ts
  src/apis/mypage/fetchPosts.ts
  src/apis/mypage/fetchResetProfileImage.ts
  src/apis/mypage/fetchUpdateNickname.ts
  src/apis/mypage/fetchUpdateProfileImage.ts
  src/apis/mypage/fetchUserInfo.ts
  src/apis/mypage/fetchWithdraw.ts
  src/app/login/set-nickname/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/posts/page.tsx
  src/app/mypage/user-info/edit-nickname/page.tsx
  src/app/mypage/user-info/page.tsx
  src/components/common/NicknameInput.tsx
  src/components/common/PropertyListSection.tsx
  src/mocks/handlers/mypage/mypageHomeHandlers.ts
  src/queries/common/useCheckUserNicknameQuery.ts
  src/queries/mypage/useBookmarkedPropertiesQuery.ts
  src/queries/mypage/useLogoutMutation.ts
  src/queries/mypage/useMypageHomeQuery.ts
  src/queries/mypage/usePostsQuery.ts
  src/queries/mypage/useResetProfileImageMutation.ts
  src/queries/mypage/useUpdateNicknameMutation.ts
  src/queries/mypage/useUpdateProfileImageMutation.ts
  src/queries/mypage/useUserInfoQuery.ts
  src/queries/mypage/useWithdrawMutation.ts
  src/types/post.ts
  src/utils/auth.ts
Labels: 📬 API, 🔨 Refactor

#79 design: 로컬스토리지에 저장하는 로직 빠져서 추가했음, app페이지와 SideBar.tsx에 유저 임시로 적용해봄
  public/icons/base-user-img.svg
  src/app/login/set-nickname/page.tsx
  src/components/chat/SideBar.tsx
Labels: 🎨 HTML & CSS

#74 feat: 필터 설정 페이지 단계별 상태 유지
  src/app/chat/filter/page.tsx
  src/app/filter/page.tsx
  src/app/page.tsx
  src/components/filter/AmountQuickSelect.tsx
  src/components/filter/BudgetStep.tsx
  src/components/filter/LocationStep.tsx
  src/components/filter/OptionSelectStep.tsx
  src/components/filter/ProgressBar.tsx
  src/hooks/useFunnel.tsx
Labels: ✨ Feature

#87 feat: 키워드로 장소 검색하기
  src/apis/filter/kakao/location.ts
  src/app/filter/page.tsx
  src/components/filter/FilterOptionCard.tsx
  src/components/filter/LocationStep.tsx
  src/components/filter/OptionSelectStep.tsx
  src/types/filter.ts
Labels: ✨ Feature, 📬 API

#92 feat: AI 추천 매물 카드 컴포넌트
  package-lock.json
  package.json
  public/icons/arrow-right-gray.svg
  src/components/chat/ChatBubble.tsx
  src/components/chat/RecommendationCard/RecommendationCard.tsx
  src/components/chat/RecommendationCard/RecommendationDots.tsx
  src/components/chat/RecommendationCard/RecommendationHeader.tsx
  src/components/chat/RecommendationCard/RecommendationList.tsx
  src/components/ui/carousel.tsx
Labels: ✨ Feature

#99 feat: property detail api 반영
  src/apis/property/detail/fetchAgent.ts
  src/apis/property/detail/fetchBasicInfo.ts
  src/apis/property/detail/fetchBrokerFee.ts
  src/apis/property/detail/fetchDescription.ts
  src/apis/property/detail/fetchFacilities.ts
  src/apis/property/detail/fetchLocation.ts
  src/apis/property/detail/fetchPropertyInfo.ts
  src/apis/property/detail/fetchTransaction.ts
  src/apis/property/detail/patchBookmark.ts
  src/apis/property/detail/postBookmark.ts
  src/app/property/[id]/(with-tabs)/page.tsx
  src/app/property/[id]/review/[reviewId]/page.tsx
  src/components/common/BookmarkButton.tsx
  src/components/common/HeartButton.tsx
  src/components/common/PropertyCard.tsx
  src/components/common/RealEstateCallButton.tsx
  src/components/property/ImageCarousel.tsx
  src/components/property/PropertyLayout.tsx
  src/components/property/detail/InfoBox.tsx
  src/components/property/detail/NotFoundProperty.tsx
  src/components/property/detail/ScrollableTabBar.tsx
  src/components/property/detail/section/AgentSection.tsx
  src/components/property/detail/section/DescriptionSection.tsx
  src/components/property/detail/section/FacilitySection.tsx
  src/components/property/detail/section/InfoSection.tsx
  src/components/property/review/CommentList.tsx
  src/components/property/review/ReviewList.tsx
  src/hooks/common/useLike.ts
  src/hooks/property/useLike.ts
  src/queries/property/detail/usePatchBookmarkmutation.ts
  src/queries/property/detail/usePostBookmarkmutation.ts
  src/types/propertyDetail.ts
  src/utils/property/dateFormat.ts
  src/utils/property/formatDate.ts
  src/utils/property/formatRelativeDate.ts
  src/utils/property/renderDash.ts
Labels: ✨ Feature, 📬 API

#95 refactor: 마이페이지 기능 추가/수정/오류해결
  public/imgs/default-profile.jpg
  public/imgs/default-profile.svg
  src/apis/common/fetchCheckUserNickname.ts
  src/apis/mypage/deletePostComment.ts
  src/apis/mypage/deletePostReview.ts
  src/apis/mypage/fetchAddRecentProperty.ts
  src/apis/mypage/fetchBookmarkedProperties.ts
  src/apis/mypage/fetchLogout.ts
  src/apis/mypage/fetchMypageHome.ts
  src/apis/mypage/fetchPostComment.ts
  src/apis/mypage/fetchPostReview.ts
  src/apis/mypage/fetchPosts.ts
  src/apis/mypage/fetchResetProfileImage.ts
  src/apis/mypage/fetchUpdateNickname.ts
  src/apis/mypage/fetchUpdateProfileImage.ts
  src/apis/mypage/fetchUserInfo.ts
  src/apis/mypage/fetchWithdraw.ts
  src/apis/real-estate/fetchRealEstateInfo.ts
  src/apis/real-estate/fetchRealEstateProperties.ts
  src/app/mypage/page.tsx
  src/app/mypage/posts/page.tsx
  src/app/mypage/user-info/edit-nickname/page.tsx
  src/app/mypage/user-info/page.tsx
  src/app/property/[id]/(with-tabs)/page.tsx
  src/app/real-estate/[id]/page.tsx
  src/components/common/EmptyListMessage.tsx
  src/components/common/PropertyCard.tsx
  src/components/common/PropertyListSection.tsx
  src/components/mypage/PostPreviewBox.tsx
  src/components/mypage/PostPreviewItem.tsx
  src/components/mypage/UserProfile.tsx
  src/components/mypage/posts/PostItem.tsx
  src/components/real-estate/RealEstateInfo.tsx
  src/hooks/common/useInfiniteScroll.ts
  src/mocks/handlers/mypage/mypageHomeHandlers.ts
  src/mocks/handlers/mypage/postsHandlers.ts
  src/mocks/handlers/mypage/userInfoHandlers.ts
  src/mocks/handlers/realEstateHandlers.ts
  src/queries/mypage/useAddRecentPropertyMutation.ts
  src/queries/mypage/useBookmarkedPropertiesQuery.ts
  src/queries/mypage/useDeletePostCommentMutation.ts
  src/queries/mypage/useDeletePostReviewMutation.ts
  src/queries/mypage/usePostCommentQuery.ts
  src/queries/mypage/usePostReviewQuery.ts
  src/queries/mypage/usePostsQuery.ts
  src/queries/mypage/useResetProfileImageMutation.ts
  src/queries/mypage/useUpdateProfileImageMutation.ts
  src/queries/real-estate/useRealEstatePropertiesQuery.ts
Labels: 🐞 BugFix, 🔨 Refactor

#100 feat: property review api 반영
  public/icons/star-fourth.svg
  public/icons/star-second.svg
  public/icons/unsend.svg
  src/apis/property/review/fetchComments.ts
  src/apis/property/review/fetchReviewList.ts
  src/apis/property/review/fetchReviewSummary.ts
  src/apis/property/review/patchReview.ts
  src/apis/property/review/postReview.ts
  src/apis/property/review/putCommentLike.ts
  src/apis/property/review/putReviewLike.ts
  src/app/property/[id]/(with-tabs)/review/page.tsx
  src/app/property/[id]/review/[reviewId]/page.tsx
  src/app/property/[id]/review/edit/[reviewId]/page.tsx
  src/app/property/[id]/review/new/page.tsx
  src/components/property/PropertyLayout.tsx
  src/components/property/review/CommentList.tsx
  src/components/property/review/EnvironmentTabs.tsx
  src/components/property/review/GoodBadSummary.tsx
  src/components/property/review/ReviewCard.tsx
  src/components/property/review/ReviewList.tsx
  src/components/property/review/ReviewSortButtons.tsx
  src/components/property/review/ThumbsButton.tsx
  src/components/ui/textarea.tsx
  src/queries/property/review/useCommentListQuery.ts
  src/queries/property/review/useDeleteCommentMutation.ts
  src/queries/property/review/usePatchReviewMutation.ts
  src/queries/property/review/usePostCommentMutation.ts
  src/queries/property/review/usePostReviewMutation.ts
  src/queries/property/review/usePutCommentLikeMutation.ts
  src/queries/property/review/usePutReviewLikeMutation.ts
  src/queries/property/review/useReviewListQuery.ts
  src/queries/property/review/useReviewSummaryQuery.ts
  src/types/commentType.ts
  src/types/reviewType.ts
  src/utils/property/starAvg.ts
Labels: ✨ Feature, 📬 API

#117 design: 온보딩페이지 제작
  public/icons/map-disabled.svg
  public/imgs/onboardingImage1.svg
  public/imgs/onboardingImage2.svg
  public/imgs/onboardingImage3.svg
  public/imgs/onboardingImage4.svg
  public/imgs/onboardingImage5.svg
  src/apis/mypage/fetchResetProfileImage.ts
  src/apis/mypage/fetchUpdateProfileImage.ts
  src/app/login/page.tsx
  src/app/mypage/user-info/edit-nickname/page.tsx
  src/app/onboarding/page.tsx
  src/components/common/PropertyListSection.tsx
  src/components/login/onboarding.tsx
  src/queries/mypage/useDeletePostReviewMutation.ts
  src/queries/mypage/useResetProfileImageMutation.ts
  src/queries/mypage/useUpdateProfileImageMutation.ts
Labels: 🎨 HTML & CSS

#96 feat: 채팅
  src/app/chat/ChatPageLayout.tsx
  src/app/chat/[chatRoomId]/page.tsx
  src/app/filter/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/chat/ChatMain.tsx
  src/components/chat/InitialFilterPrompt.tsx
  src/components/chat/MessageList.tsx
  src/components/chat/RecommendationCard/RecommendationCard.tsx
  src/components/chat/RecommendationCard/RecommendationHeader.tsx
  src/components/chat/RecommendationCard/RecommendationList.tsx
  src/components/chat/SideBar.tsx
  src/components/chat/SideBarItem.tsx
  src/components/common/LoadingDots.tsx
  src/components/filter/BudgetStep.tsx
  src/components/filter/FilterOptionCard.tsx
  src/components/filter/LocationStep.tsx
  src/components/filter/PropertySearchLoading.tsx
  src/components/ui/chatTextarea.tsx
  src/hooks/useFunnel.tsx
  src/layout/Header.tsx
  src/queries/chat/useChatDataQuery.ts
  src/queries/chat/useChatListQuery.ts
  src/queries/chat/useChatResponseQuery.ts
  src/queries/chat/useCreateChatMutation.ts
  src/queries/chat/useDeleteChatMutation.ts
  src/queries/chat/useSendMessageMutation.ts
  src/queries/chat/useUpdateChatTitleMutation.ts
  src/queries/filter/useSetFilterMutation.ts
  src/types/chat.ts
  src/types/filter.ts
  src/utils/common/highlightSearchKeyword.tsx
  src/utils/common/highlightSearchText.tsx
Labels: ✨ Feature

#124 feat: 채팅 내 지도 뷰어 및 다이얼로그 연결
  src/app/chat/ChatPageLayout.tsx
  src/components/chat/ChatMain.tsx
  src/components/chat/RecommendationCard/RecommendationCard.tsx
  src/components/chat/RecommendationCard/RecommendationHeader.tsx
  src/components/chat/RecommendationCard/RecommendationList.tsx
  src/types/chat.ts
Labels: ✨ Feature

#126 feat: 결과 확인하기 로딩 화면 헤더 수정
  src/app/filter/page.tsx
  src/components/filter/BudgetStep.tsx
Labels: ✨ Feature
